// <auto-generated />
namespace LojaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class alter3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter3));
        
        string IMigrationMetadata.Id
        {
            get { return "201805262210276_alter3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
